"""``scripts/paper_tables.py`` (E5.3, #44): the manuscript's table fragments."""

import re
import sys
from functools import cache
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from heat_interfaces.results_cache import read_results  # noqa: E402
from paper_tables import TABLES, figs, fixed, ratio, sci, sci_range  # noqa: E402

DATA = ROOT / "paper" / "data"


class Data:
    """``paper_figures.py``'s reader: a results file's tables by name, read once."""

    def __init__(self, root: Path = DATA):
        self.root = root

    @cache  # noqa: B019 (one instance per module)
    def tables(self, name: str) -> dict:
        return read_results(self.root / name)["tables"]


DATA_READER = Data()


def test_sci_rounds_rolls_over_and_marks_what_is_missing():
    assert sci(1.598e-5) == r"$\sci{1.60}{-5}$"
    assert sci(3.3253e-6) == r"$\sci{3.33}{-6}$"
    assert sci(9.996e-3) == r"$\sci{1.00}{-2}$"  # not \sci{10.00}{-3}
    assert sci(9.96e-3, 2) == r"$\sci{1.0}{-2}$"
    assert sci(-2.5e-3, 2) == r"$\sci{-2.5}{-3}$"
    assert sci(None) == "--" and sci(0.0) == "$0$"
    assert sci_range([1.3e4, 1.7e4]) == r"$(1.3$--$1.7) \times 10^{4}$"
    assert sci_range([8.0e3, 3.2e4]) == r"$\sci{8.0}{3}$--$\sci{3.2}{4}$"


def test_ratios_orders_and_minus_signs():
    assert ratio(6741.6) == "6742"  # the notes' whole numbers, not 6740
    assert ratio(0.9384) == "0.938" and ratio(0.08123) == "0.081"
    assert ratio(0.99962) == "1.00" and ratio(1.0496) == "1.05"
    assert ratio(3.0e-5) == r"$\sci{3.0}{-5}$" and ratio(None) == "--"
    assert figs(0.0071, 2) == "0.0071"
    assert fixed(4.7651) == "4.77" and fixed(-0.28) == "$-0.28$"


def _columns(colspec: str) -> int:
    """The number of columns of a spec, its ``@{...}`` expressions aside."""
    out, depth, skip = 0, 0, False
    for i, ch in enumerate(colspec):
        if ch == "@" and colspec[i + 1] == "{":
            skip = True
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                skip = False
        elif depth == 0 and not skip and ch in "lrc":
            out += 1
    return out


def _spans(line: str) -> int:
    total = 0
    for cell in line.removesuffix(r"\\").split("&"):
        m = re.match(r"\s*\\multicolumn\{(\d+)\}", cell)
        total += int(m.group(1)) if m else 1
    return total


@pytest.mark.parametrize("name", sorted(TABLES))
def test_every_fragment_is_one_booktabs_tabular_from_its_files(name):
    table = TABLES[name]
    text = table.write(DATA_READER)
    assert text == table.write(DATA_READER)  # deterministic
    assert text.isascii(), [c for c in text if not c.isascii()]
    lines = text.splitlines()
    header = lines[0]
    assert header.startswith("% GENERATED by scripts/paper_figures.py from ")
    assert header.endswith("; do not edit.")
    named = re.findall(r"paper/data/([\w.]+\.json)", header)
    assert tuple(named) == table.files
    assert all((DATA / f).exists() for f in named)
    begin = next(i for i, line in enumerate(lines) if line.startswith(r"\begin"))
    assert all(line.startswith("% ") for line in lines[1:begin])
    assert text.count(r"\begin{tabular}") == text.count(r"\end{tabular}") == 1
    assert lines[begin + 1] == r"\toprule" and lines[-2:] == [
        r"\bottomrule",
        r"\end{tabular}",
    ]
    assert r"\midrule" in text
    spec = re.match(r"\\begin\{tabular\}\{(.*)\}$", lines[begin]).group(1)
    columns = _columns(spec)
    rows = [line for line in lines[begin + 1 : -1] if line.endswith(r"\\")]
    assert rows
    for line in rows:
        assert _spans(line) == columns, (name, line)
    assert text.count("{") == text.count("}"), name


def test_key_cells_are_the_notes_numbers():
    # Stiff note §5.1's snapshot table and §5.3's statements 4, 8 and 9, as the
    # notes quote them (E4.10); a fragment that moved would move these.
    snapshot = TABLES["tab_2d_snapshot.tex"].write(DATA_READER)
    assert r"seeds & $\sci{3.33}{-6}$ & $\sci{2.27}{-5}$ & $(0.259, 0.980)$" in snapshot
    assert r"$\sci{2.63}{-3}$" in snapshot and r"$\sci{3.71}{-2}$" in snapshot
    seeds = TABLES["tab_2d_seeds.tex"].write(DATA_READER)
    assert r"fit & 4.77 & 4.23 & 4.31 & 4.23 & 4.48 &  \\" in seeds
    assert r"fit, 8 $N$ & 4.54" in seeds
    curved = TABLES["tab_2d_curved.tex"].write(DATA_READER)
    for value in ("7.18}{-9", "3.01}{-8", "3.00}{-8", "2.69}{-8"):
        assert value in curved
    ring = TABLES["tab_2d_ring.tex"].write(DATA_READER)
    assert "& 4.43 &" in ring and "& 4.71 &" in ring
    one_d = TABLES["tab_1d_snapshot.tex"].write(DATA_READER)
    assert r"seeds & $\sci{2.95}{-8}$" in one_d
    knee = TABLES["tab_1d_knee.tex"].write(DATA_READER)
    assert "$c = 8.78890$ measured" in knee
