"""The 1-D heat operator ``d/dx (alpha d/dx)`` on [-1, 1] with Dirichlet ends.

``domain``: grids and piecewise materials (dissertation eq. 64, 75);
``operators``: FD4 ``Dx``, ``A``, the naive ``Dx A Dx`` (eq. 76), the direct
stencil and the §4.1 jump-aware operator; ``interface``: the coefficient-space
algebra behind it (continuity matrices, the translated basis, the stencil
solve); ``solve``: Dirichlet rows and the sparse solve; ``exact``: the
quadrature reference ``u = A + B ∫ dξ/alpha`` and the piecewise Chebyshev
reference for the parabolic problems, cached as ``ParabolicReference``;
``march``: BD4 and RK4 with time-dependent Dirichlet ends and the BD4
stability region. ``SmoothEdges`` (E3.2) is the stiff-edge medium; ``stiff``
(E3.4) marches the seeds through it and builds the seed operator, with
``build_operator`` dispatching by name; ``treatments`` (E3.5) are the
coefficient treatments the naive operator samples (cell means, the widened
edge) and the finite-volume twin with exact face conductances.
"""

from .domain import (
    DISSERTATION_BC,
    EDGE_CUTS,
    PLACEMENT_TOL,
    TANH_REACH,
    Constant,
    Grid1D,
    Medium1D,
    PiecewiseAlpha,
    Sinusoid,
    Smooth,
    SmoothEdges,
    dissertation_alpha,
    eabe_alpha,
    equispaced_grid,
    grid_for,
    jump_alpha,
    matlab_alpha,
    node_counts,
)
from .exact import (
    RADAU_ATOL,
    RADAU_RTOL,
    ChebyshevPieces,
    ParabolicReference,
    alpha_integral,
    chebyshev_equilibrium,
    chebyshev_lobatto,
    chebyshev_parabolic,
    edge_resistance_deficit,
    equilibrium_exact,
    equilibrium_flux,
    inverse_alpha_integral,
    parabolic_reference,
)
from .interface import (
    Jump,
    Region,
    coefficient_dx,
    coefficient_operator,
    continuity_conditions,
    continuity_matrix,
    multiplication_matrix,
    shift_matrix,
    stencil_weights,
    translated_basis,
    translation_matrix,
)
from .march import (
    bd4_amplification,
    bd4_march,
    bd4_stability_boundary,
    constant_boundary,
    interior_operator,
    march_steps,
    ramp_boundary,
    rk4_dt_limit,
    rk4_march,
    smooth_step,
)
from .operators import (
    alpha_matrix,
    derivative_matrix,
    direct_operator,
    dx_matrix,
    dxx_matrix,
    jump_aware_operator,
    naive_operator,
    straddling_windows,
)
from .solve import dirichlet_system, normalized_l2, rms_error, solve_equilibrium
from .stiff import (
    EDGE_STOP,
    OPERATOR_MODES,
    SEED_ATOL,
    SEED_RTOL,
    build_operator,
    edge_width,
    seed_basis,
    seed_operator,
    seed_profiles,
    seed_weights,
    seeded_windows,
)
from .treatments import (
    LinearPiece,
    NodalAlpha,
    arithmetic_cells,
    cell_windows,
    face_conductance_operator,
    face_conductances,
    harmonic_cells,
    widened_edge,
)

__all__ = [
    "DISSERTATION_BC",
    "EDGE_CUTS",
    "EDGE_STOP",
    "OPERATOR_MODES",
    "PLACEMENT_TOL",
    "RADAU_ATOL",
    "RADAU_RTOL",
    "SEED_ATOL",
    "SEED_RTOL",
    "TANH_REACH",
    "ChebyshevPieces",
    "Constant",
    "Grid1D",
    "Jump",
    "LinearPiece",
    "Medium1D",
    "NodalAlpha",
    "ParabolicReference",
    "PiecewiseAlpha",
    "Region",
    "Sinusoid",
    "Smooth",
    "SmoothEdges",
    "alpha_integral",
    "alpha_matrix",
    "arithmetic_cells",
    "bd4_amplification",
    "bd4_march",
    "bd4_stability_boundary",
    "build_operator",
    "cell_windows",
    "chebyshev_equilibrium",
    "chebyshev_lobatto",
    "chebyshev_parabolic",
    "coefficient_dx",
    "coefficient_operator",
    "constant_boundary",
    "continuity_conditions",
    "continuity_matrix",
    "derivative_matrix",
    "direct_operator",
    "dirichlet_system",
    "dissertation_alpha",
    "dx_matrix",
    "dxx_matrix",
    "eabe_alpha",
    "edge_resistance_deficit",
    "edge_width",
    "equilibrium_exact",
    "equilibrium_flux",
    "equispaced_grid",
    "face_conductance_operator",
    "face_conductances",
    "grid_for",
    "harmonic_cells",
    "interior_operator",
    "march_steps",
    "inverse_alpha_integral",
    "jump_alpha",
    "jump_aware_operator",
    "matlab_alpha",
    "multiplication_matrix",
    "naive_operator",
    "node_counts",
    "normalized_l2",
    "parabolic_reference",
    "ramp_boundary",
    "rk4_dt_limit",
    "rk4_march",
    "rms_error",
    "seed_basis",
    "seed_operator",
    "seed_profiles",
    "seed_weights",
    "seeded_windows",
    "shift_matrix",
    "smooth_step",
    "solve_equilibrium",
    "stencil_weights",
    "straddling_windows",
    "translated_basis",
    "translation_matrix",
    "widened_edge",
]
