"""The 2-D heat operator ``div(alpha grad)`` on the x-periodic strip, Dirichlet rows.

``domain``: curves (flat and sine graphs, circles), the closed-band
materials of the three 2016 cases, the case geometries and the node sets
with straddling rows (dissertation §5.4, EABE §3); ``neighbors``: nearest
neighbours periodic in x only. RBF-FD weights, interface-aware stencils,
operators, solvers, references and seeds follow in E2.2 onward.
"""

from .domain import (
    CASES,
    COOLING_RADIUS,
    DIRICHLET,
    FREE,
    RING,
    ROW,
    ROW_OFFSETS,
    ROW_STAGGER,
    STEP_SCALE,
    STRADDLE_FRACTION,
    STRIP,
    Band,
    Circle,
    Constant2D,
    Curve,
    Domain,
    FlatLine,
    NodeSet,
    Piece2D,
    Row,
    SineGraph,
    SineProduct,
    build_node_set,
    case1,
    case2,
    case3,
    row_count,
    step_delta,
    straddle_count,
)
from .neighbors import (
    PERIOD,
    knn,
    nearest_spacing,
    offsets,
    periodic_dx,
    periodic_tree,
    wrap_x,
)

__all__ = [
    "CASES",
    "COOLING_RADIUS",
    "DIRICHLET",
    "FREE",
    "PERIOD",
    "RING",
    "ROW",
    "ROW_OFFSETS",
    "ROW_STAGGER",
    "STEP_SCALE",
    "STRADDLE_FRACTION",
    "STRIP",
    "Band",
    "Circle",
    "Constant2D",
    "Curve",
    "Domain",
    "FlatLine",
    "NodeSet",
    "Piece2D",
    "Row",
    "SineGraph",
    "SineProduct",
    "build_node_set",
    "case1",
    "case2",
    "case3",
    "knn",
    "nearest_spacing",
    "offsets",
    "periodic_dx",
    "periodic_tree",
    "row_count",
    "step_delta",
    "straddle_count",
    "wrap_x",
]
