"""The 2-D heat operator ``div(alpha grad)`` on the x-periodic strip, Dirichlet rows.

``domain``: curves (flat and sine graphs, circles), the closed-band
materials of the three 2016 cases, the case geometries and the node sets
with straddling rows (dissertation §5.4, EABE §3); ``neighbors``: nearest
neighbours periodic in x only; ``rbf``: Gaussian RBF-FD weights with
polynomial augmentation, batched over stencils (EABE eq. 2, 31);
``operators``: stencil groups (42 / degree 5 inside, 30 / degree 4 near a
Dirichlet curve), sparse ``Dx``, ``Dy``, the Laplacian, ``A``, the naive
``Dx A Dx + Dy A Dy`` (plan D3), the direct ``α ∇² + ∇α·∇`` and the
Dirichlet rows; ``interface``: the translated polynomial bases across
interfaces with curvature and the multi-interface chain (dissertation §5.3,
EABE §2.2.3) and ``operators.interface_aware_operator``; ``solve``: the
SuperLU equilibrium solve; ``exact``: the separable piecewise-exponential
solutions of the control and of case 1 (EABE eq. 34), with the warped
Gaussians of EABE §2.2.4 (``interface.Warp``) on by default. BD4 and the
case drivers follow in E2.5 onward.
"""

from .domain import (
    CASES,
    COOLING_RADIUS,
    DIRICHLET,
    FREE,
    RING,
    ROW,
    ROW_OFFSETS,
    ROW_STAGGER,
    STEP_SCALE,
    STRADDLE_FRACTION,
    STRIP,
    Band,
    Circle,
    Constant2D,
    Curve,
    Domain,
    FlatLine,
    NodeSet,
    Piece2D,
    Row,
    SineGraph,
    SineProduct,
    build_node_set,
    case1,
    case2,
    case3,
    row_count,
    step_delta,
    straddle_count,
)
from .exact import LayeredExact, case1_exact, control_exact
from .interface import (
    Frame,
    LocalInterface,
    Region,
    Warp,
    build_warp,
    coefficient_dx,
    coefficient_dy,
    coefficient_operator,
    continuity_conditions,
    continuity_matrix,
    frame_at,
    frame_change,
    interface_expansion,
    local_interface,
    local_taylor,
    multiplication_matrix,
    restriction_matrix,
    stencil_weights,
    substitution_matrix,
    table_to_vector,
    translated_basis,
    translation_matrix,
    vector_to_table,
)
from .neighbors import (
    PERIOD,
    knn,
    nearest_spacing,
    offsets,
    periodic_dx,
    periodic_tree,
    wrap_x,
)
from .operators import (
    BOUNDARY_KIND,
    BOUNDARY_ZONE,
    INTERFACE_KIND,
    INTERIOR_KIND,
    StencilGroup,
    Stencils,
    alpha_matrix,
    boundary_zone,
    build_stencils,
    derivative_matrices,
    derivative_matrix,
    direct_operator,
    dirichlet_system,
    dirichlet_values,
    interface_aware_operator,
    interface_crossings,
    laplacian_operator,
    naive_operator,
)
from .rbf import (
    BOUNDARY,
    GA_SHAPE,
    INTERIOR,
    ITERATIVE,
    OPERATORS,
    StencilSpec,
    augmented_solve,
    gaussian,
    gaussian_derivative,
    polynomial_block,
    polynomial_count,
    polynomial_exponents,
    polynomial_rhs,
    rbf_fd_weights,
)
from .solve import normalized_l2, rms_error, solve_equilibrium

__all__ = [
    "BOUNDARY",
    "BOUNDARY_KIND",
    "BOUNDARY_ZONE",
    "CASES",
    "COOLING_RADIUS",
    "DIRICHLET",
    "FREE",
    "GA_SHAPE",
    "INTERFACE_KIND",
    "INTERIOR",
    "INTERIOR_KIND",
    "ITERATIVE",
    "OPERATORS",
    "PERIOD",
    "RING",
    "ROW",
    "ROW_OFFSETS",
    "ROW_STAGGER",
    "STEP_SCALE",
    "STRADDLE_FRACTION",
    "STRIP",
    "Band",
    "Circle",
    "Constant2D",
    "Curve",
    "Domain",
    "FlatLine",
    "Frame",
    "LayeredExact",
    "LocalInterface",
    "NodeSet",
    "Piece2D",
    "Region",
    "Warp",
    "Row",
    "SineGraph",
    "SineProduct",
    "StencilGroup",
    "StencilSpec",
    "Stencils",
    "alpha_matrix",
    "augmented_solve",
    "boundary_zone",
    "build_node_set",
    "build_stencils",
    "case1",
    "case1_exact",
    "case2",
    "case3",
    "coefficient_dx",
    "coefficient_dy",
    "coefficient_operator",
    "continuity_conditions",
    "continuity_matrix",
    "control_exact",
    "derivative_matrices",
    "derivative_matrix",
    "direct_operator",
    "dirichlet_system",
    "dirichlet_values",
    "frame_at",
    "frame_change",
    "gaussian",
    "gaussian_derivative",
    "interface_aware_operator",
    "interface_crossings",
    "interface_expansion",
    "knn",
    "laplacian_operator",
    "local_interface",
    "local_taylor",
    "multiplication_matrix",
    "naive_operator",
    "nearest_spacing",
    "normalized_l2",
    "offsets",
    "periodic_dx",
    "periodic_tree",
    "polynomial_block",
    "polynomial_count",
    "polynomial_exponents",
    "polynomial_rhs",
    "rbf_fd_weights",
    "restriction_matrix",
    "rms_error",
    "row_count",
    "solve_equilibrium",
    "stencil_weights",
    "step_delta",
    "straddle_count",
    "substitution_matrix",
    "table_to_vector",
    "build_warp",
    "translated_basis",
    "translation_matrix",
    "vector_to_table",
    "wrap_x",
]
